version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sweetshop_db
    restart: always
    environment:
      POSTGRES_USER: sweetshop
      POSTGRES_PASSWORD: sweetshop
      POSTGRES_DB: sweetshop
    ports:
      - "5433:5432"
    volumes:
      - sweetshop_data:/var/lib/postgresql/data

volumes:
  sweetshop_data:
